config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'mad_money' => 'welcome#index'
  get 'sign_up' => 'users#new', :as => 'mr_signy'
  get 'log_in' => 'sessions#new', :as => 'mr_logy'

  put 'upvote/:id' => 'posts#upvote', :as => "upvote"
  put 'downvote/:id' => 'posts#downvote', :as => "downvote"

  delete 'this_is_the_sign_out_route' => 'sessions#destroy', :as => 'sign_out'

  resources :sessions
  resources :posts do
    resources :comments
    resources :votings
  end
  resources :products 
  resources :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :content
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  has_many :votings
  has_many :comments, :dependent => :destroy
  validates_presence_of :title, :article

  def self.create_from_last_product(user_name)
    @product = Product.last
    self.create(title: "#{user_name}'s Invention Idea: #{@product.name}", article: "#{@product.description}", user_id: @product.user_id, product_id: @product.id)
  end 

  def increment_rating
    self.update(rating: (self.rating +=1))
  end

  def decrease_rating
    self.update(rating: (self.rating -=1))
  end

  def destroy_post_product_and_comments
    self.comments.delete_all
    self.product.delete
    self.delete
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :posts
  
  validates_presence_of :name, :price, :description

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products
  has_many :posts, through: :products
  has_many :comments
  has_many :votings

  validates_presence_of :name, presence: true

  validates_uniqueness_of :email
  validates_presence_of :email, presence: true

  has_secure_password
end

app/models/voting.rb
class Voting < ActiveRecord::Base
  validates :user_id, presence: true
  validates :post_id, presence: true
  belongs_to :user
  belongs_to :post

  attr_reader :post, :user

  def self.user_has_voting_record?
    !!Voting.where(params).first
  end

  def self.current_vote
    Voting.where(params).first.voting_record
  end

  def self.upvoting_record
    Voting.find_or_create_by(params).update(voting_record: true)
    @post.increment_rating
  end

  def self.downvoting_record
    Voting.find_or_create_by(params).update(voting_record: false)
    @post.decrease_rating
  end

  def self.upvote_post(post, user)
    @post = post
    @user = user
    if !user_has_voting_record? 
      upvoting_record
    elsif user_has_voting_record? && !current_vote
      upvoting_record
    else
    end
  end

  def self.downvote_post(post, user)
  @post = post
  @user = user
    if !user_has_voting_record? 
      downvoting_record
    elsif user_has_voting_record? && current_vote
      downvoting_record
    else
    end
  end

  private

  def self.params
    params = {user_id: @user.id, post_id: @post.id}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_present?
    !!current_user
  end
  helper_method :user_present?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    Comment.find(params[:id]).delete
    redirect_to post_path(params[:post_id])
  end 

  private

  def comment_params
    params.require(:post).require(:comment).permit(:content, :post_id, :user_id )
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
  end

  def index
    redirect_to root_path
  end

  def upvote
  @post = Post.find(params[:id])
    if user_present?
      @post.votings.upvote_post(@post, current_user)
      redirect_to root_path
    else user_present?
      redirect_to root_path, :notice => "You need to be signed in to upvote!"
    end
  end

  def downvote
  @post = Post.find(params[:id]) 
    if user_present?
      @post.votings.downvote_post(@post, current_user)
      redirect_to root_path
    else
      redirect_to root_path, :notice => "You need to be signed in to downvote!"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path, :notice => "Your new post has been added!"
    elsif post_params[:title].empty? || post_params[:article].empty?
      redirect_to edit_post_path(@post), :notice => "Nothing can be blank."
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy_post_product_and_comments
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :article)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @post = Post.create_from_last_product(current_user.name)
      @product.update(post_id: @post.id)
      redirect_to edit_post_path(@post)
    elsif
      product_params[:name].empty? || product_params[:price].empty? || product_params[:description].empty?
      render :new, :notice => "Please fill in all the fields."
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to edit_post_path(@product.post_id)
    elsif product_params[:name].empty? || product_params[:price].empty? || product_params[:desciption].empty?
      redirect_to edit_product_path(@product), :notice => "Nothing can be blank."
    else
      render :edit
    end
  end

  def product_params
    params.require(:product).permit(:name, :price, :description, :user_id)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Welcome back, #{@user.name}"
    else
      redirect_to mr_logy_path, :notice => "Invalid email or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have successfully logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      if user_params[:name].empty?
        redirect_to mr_signy_path(@notice), :notice => "Please fill in a first name."
      elsif user_params[:email].empty?
        redirect_to mr_signy_path(@notice), :notice => "Please fill in an email."
      elsif user_params[:password].empty? || user_params[:password_confirmation].empty?
        redirect_to mr_signy_path(@notice), :notice => "Please fill in both password fields."
      elsif user_params[:password] != user_params[:password_confirmation]
        redirect_to mr_signy_path(@notice), :notice => "It seems your passwords aren't the same..."
      else
        redirect_to mr_signy_path(@notice), :notice => "It looks like that email is taken, sorry." 
      end
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :password, :email, :password_confirmation)
  end
end

app/controllers/votings_controller.rb
class VotingsController < ApplicationController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.order(rating: :desc)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
<h6>Created by Adam Winters</h6>
<a href='https://github.com/mbrickenworthe' class= "links"><%= image_tag('/assets/pictures/github.png', size: "16x16")%></a>
<a href='https://learn.co/mbrickenworthe' class= "links"><%= image_tag('/assets/pictures/learn.png', size: "16x16")%></a>
<a href='https://www.linkedin.com/in/adamrwinters' class= "links"><%= image_tag('/assets/pictures/linkedin.png', size: "16x16")%></a>
<a href='https://teamtreehouse.com/adamw' class= "links"><%= image_tag('/assets/pictures/treehouse.png', size: "16x16")%></a>
<%= mail_to "adamwinters456@gmail.com", image_tag('/assets/pictures/gmail.png', size: "16x16", alt: "Gmail"), :class => "links"%>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="links">
  <%if user_present? == false%>
  <%= link_to "New User? Click Here!", mr_signy_path %></br></br>
  <%= link_to "Already a User? Click Here", mr_logy_path%></br></br>
  <%end%>

  <%= link_to "Click Here for Home Page", root_path%></br>
  <%if user_present?%>
  <div>Welcome, <%= current_user.name%>!</div>
  <%= link_to "Sign Out", sign_out_path, method: :delete%>
  <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/posts/edit.html.erb
<p>We've gone ahead and created a post for you about your invention. Everything look good?</p>

<%= notice%>

<%= form_for(@post) do |f|%>

<%= f.label "Name of the Article" %>
<%= f.text_field :title, :value => "#{@post.title}"%></br>
<%= f.label "Article Content" %>
<%= f.text_area :article, :value => "#{@post.article}"%></br>
<%= f.submit "Everything looks great!"%>

<%end%>

app/views/posts/show.html.erb
<%= notice%></br>

<%if user_present?%>
  <%if current_user.id == @post.user_id%>
  <%= link_to "Edit Invention", edit_product_path(@post.product_id)%></br>
  <%= link_to "Edit Post", edit_post_path(@post)%>
  <%end%>
<%end%>


<h3><%= @post.title%></h3>
<p><%= @post.article%></p>



</br>
<%= form_for @post, url: new_post_comment_path(@post), method: :get do |f|%>
  <% f.fields_for :comment do |com|%>
    <%= com.label "Comment"%>
    <%= com.text_field :content%></br>
    <%= com.hidden_field :post_id, :value => @post.id %>
    <%if user_present?%>
      <%= com.hidden_field :user_id, :value => current_user.id %>
    <%end%>
    <%= com.submit "Create Comment"%>
  <%end%>
<%end%>



<%if @comments.count > 0%>
  <ul><% @comments.each do |comment|%>
    <li><%= comment.content%></li>
        <% if comment.user == nil %>
          <%= "Anonymous" %>
        <% else %>
          <%= comment.user.name%>
        <% end %>
        <%= comment.created_at.strftime("%b %d, %Y") %>
        <%if user_present? && current_user.id == comment.user_id %>
          <%= link_to 'Destroy', post_comment_path(@post, comment), :method => :delete %>
        <%end%>
  <%end%>
  </ul>
<%end%>

app/views/products/edit.html.erb
<p>Want to tweek that invention??</p>

<%= notice%>

<%= form_for(@product) do |f|%>

<%= f.label "Name" %>
<%= f.text_field :name, :value => "#{@product.name}"%></br>
<%= f.label "Selling Price" %>
<%= f.text_field :price, :value => "#{@product.price}"%></br>
<%= f.label "Description" %>
<%= f.text_area :description, :value => "#{@product.description}"%></br>
<%= f.submit "Now that's a better invention!"%>

<%end%>

app/views/products/new.html.erb
<p>Add the details to your new invention here!</p>

<%= notice %></br></br>

<%= form_for(@product) do |f|%>
  <%= f.label "Name of Invention"%>
  <%= f.text_field :name%></br>
  <%= f.label "Price $"%>
  <%= f.text_field :price%></br>
  <%= f.label "General Description of the Invention"%>
  <%= f.text_area :description%></br>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit "Create the Invention!"%>
<%end%>

app/views/users/new.html.erb
<%= notice %></br></br>

<%=form_for(@user) do |f|%>

<table>
<tr>
  <td><%= f.label "First Name:" %></td>
  <td><%= f.text_field :name%></td>
  <td><%= f.label "Password:" %></td>
  <td><%= f.password_field :password %></td>
</tr>
<tr>
  <td><%= f.label "Your Email Address:" %></td>
  <td><%= f.text_field :email %></td>
  <td><%= f.label "Confirm your password:" %></td>
  <td><%= f.password_field :password_confirmation %></td>
</tr>
</table>
  <%= f.submit "Create an Account" %>
<%end%>

app/views/welcome/index.html.erb
<html>
<body>
<strong><h2>Inventors' Inventory</h2></strong>
<%= notice %>

<%if user_present?%><p><%= link_to "Create a New Invention!", new_product_path%></p><%end%>

<h3><strong>Product Posts</strong></h3>
<% if @posts%>
-------------------------------------------
<% if !(user_present?) %>
  <div> 
    Sign In to Add Your Own Posts!
  </div>
<% end %>
  <% @posts.each do |post|%></br>
  -------------------------------------------
    <a href="/posts/<%=post.id%>"><h4><%= post.title%></h4></a>
    <p><%=post.article%></p>
    <%if user_present? && current_user.id == post.user_id %>
      Rating: <%=post.rating%>
    <%else%>
      <%=link_to "Upvote", upvote_path(post), method: :put, :class => "votes" %>
      Rating: <%=post.rating%>
      <%=link_to "Downvote", downvote_path(post), method: :put, :class => "votes" %>
    <%end%>
    <%if user_present? && current_user.id == post.user_id%></br>
      <%=link_to "Edit Post", edit_post_path(post)%></br>
      <%=link_to "Delete Invention and Post", "/posts/#{post.id}", method: :delete%>
    <%end%>
  <%end%>
<%end%>
</body>
</html>